name: Comment on Pull Request

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    # - name: Set Automatic Release Tag
    #   run: echo "automatic_release_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    #   if: startsWith(github.ref, 'refs/tags/')

    # - name: Comment on Pull Request
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     automatic_release_tag: "latest"
    #     files: "coverage/lcov-report/index.html"
    #     release-notes: "Jest Coverage Report"
    #     title: "Coverage Report"
    - name: Comment on Pull Request
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const coverageReport = fs.readFileSync('coverage/lcov-report/index.html', 'utf-8');
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Jest Coverage Report:\n\n${coverageReport}`,
          });
