name: Comment on Pull Request

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Comment on Pull Request
      uses: marvinpinto/action-automatic-releases@latest
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        files: "coverage/lcov-report/index.html"
        release-notes: "Jest Coverage Report"
        title: "Coverage Report"
